-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-05-30 00:08:08 EDT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE client (
    num_client NUMBER NOT NULL,
    prenom     VARCHAR2(50),
    nom        VARCHAR2(50),
    telephone  VARCHAR2(50),
    adresse    VARCHAR2(50)
);

INSERT INTO client (num_client, prenom, nom, telephone, adresse) VALUES (1,'Joe','Johnson','123-456-7890','12345 Rue Muir');
INSERT INTO client (num_client, prenom, nom, telephone, adresse) VALUES (2,'LeBron','James','156-224-3366','10555 Avenue de Bois-de-Boulogne');
INSERT INTO client (num_client, prenom, nom, telephone, adresse) VALUES (3,'Christian','Lemieux','826-102-1688','3833 Rue Cecil');
INSERT INTO client (num_client, prenom, nom, telephone, adresse) VALUES (4,'Jimmy','Butler','192-168-8927','718 Avenue Tyler');
INSERT INTO client (num_client, prenom, nom, telephone, adresse) VALUES (5,'Jean-Patrick','Gagnon','360-229-5566','4219 Rue Red Hawk');
INSERT INTO client (num_client, prenom, nom, telephone, adresse) VALUES (6,'Emile','Bergeron','555-666-7789','2283 Rue Tully');

ALTER TABLE client ADD CONSTRAINT client_pk PRIMARY KEY ( num_client );

CREATE TABLE commande (
    id_commande       NUMBER NOT NULL,
    entrepot          VARCHAR2(50),
    date_livraison    DATE,
    client_num_client NUMBER NOT NULL
);

INSERT INTO commande (id_commande, entrepot, date_livraison, client_num_client) VALUES (1,'Montr�al',to_date('09062024','DD-MM-YYYY'),1);
INSERT INTO commande (id_commande, entrepot, date_livraison, client_num_client) VALUES (2,'Laval',to_date('13072024','DD-MM-YYYY'),2);
INSERT INTO commande (id_commande, entrepot, date_livraison, client_num_client) VALUES (3,'Los Angeles',to_date('29052024','DD-MM-YYYY'),3);
INSERT INTO commande (id_commande, entrepot, date_livraison, client_num_client) VALUES (4,'Miami',to_date('10062024','DD-MM-YYYY'),4);
INSERT INTO commande (id_commande, entrepot, date_livraison, client_num_client) VALUES (5,'San Francisco',to_date('21072024','DD-MM-YYYY'),5);
INSERT INTO commande (id_commande, entrepot, date_livraison, client_num_client) VALUES (6,'Boston',to_date('11062024','DD-MM-YYYY'),6);

ALTER TABLE commande ADD CONSTRAINT commande_pk PRIMARY KEY ( id_commande );

CREATE TABLE ordinateurs (
    numero               NUMBER NOT NULL,
    marque               VARCHAR2(30),
    sys_exploitation     VARCHAR2(15),
    couleur              VARCHAR2(20),
    prix                 NUMBER,
    description          VARCHAR2(100),
    commande_id_commande NUMBER NOT NULL
);

INSERT INTO ordinateur (numero, marque, sys_exploitation, couleur,prix,description,commande_id_commande) VALUES (1,'Apple','MacOS Ventura','Gris',1500,'Macbook Pro 2018, 16 GB RAM, 1 TB SSD',1);
INSERT INTO ordinateur (numero, marque, sys_exploitation, couleur,prix,description,commande_id_commande) VALUES (2,'Dell','Windows 10','Noir',1859,'Dell XPS 15, 24 GB RAM, 1 TB SSD',2);
INSERT INTO ordinateur (numero, marque, sys_exploitation, couleur,prix,description,commande_id_commande) VALUES (3,'Asus','Windows 11','Noir',2500,'Zenbook Pro 15 OLED, 32 GB RAM, 2 TB SSD',3);

 
ALTER TABLE ordinateurs ADD CONSTRAINT ordinateurs_pk PRIMARY KEY ( numero );

CREATE TABLE tablette (
    numero               NUMBER NOT NULL,
    couleur              VARCHAR2(30),
    prix                 NUMBER,
    marque               VARCHAR2(30),
    cameras              NUMBER,
    description          VARCHAR2(100),
    commande_id_commande NUMBER NOT NULL
);

INSERT INTO tablette (numero, couleur, prix, marque,cameras,description,commande_id_commande) VALUES (1,'Noir',2500,'Apple',3,'iPad Pro 2024, 13 pouces, 512 GB SSD, iPadOS 17',4);
INSERT INTO tablette (numero, couleur, prix, marque,cameras,description,commande_id_commande) VALUES (2,'Gris',1600,'Apple',2,'iPad Air 2024, 11 pouces, 256 GB SSD, iPadOS 17',5);
INSERT INTO tablette (numero, couleur, prix, marque,cameras,description,commande_id_commande) VALUES (3,'Noir',600,'Samsung',2,'Galaxy Tab S9 FE+, 12.4 pouces,128 GB SSD, Android 14',6);

 

ALTER TABLE tablette ADD CONSTRAINT tablette_pk PRIMARY KEY ( numero );

ALTER TABLE commande
    ADD CONSTRAINT commande_client_fk FOREIGN KEY ( client_num_client )
        REFERENCES client ( num_client );

ALTER TABLE ordinateurs
    ADD CONSTRAINT ordinateurs_commande_fk FOREIGN KEY ( commande_id_commande )
        REFERENCES commande ( id_commande );

ALTER TABLE tablette
    ADD CONSTRAINT tablette_commande_fk FOREIGN KEY ( commande_id_commande )
        REFERENCES commande ( id_commande );

------------------------------------------------Activation du REST------------------------------------------------
BEGIN
  ORDS.enable_schema(
    p_enabled             => TRUE,
    p_schema              => 'RESTSCOTT',
    p_url_mapping_type    => 'BASE_PATH',
    p_url_mapping_pattern => 'hr2',
    p_auto_rest_auth      => FALSE
  );
    
  COMMIT;
END;
/

----------------------table client----------------------
BEGIN
  ORDS.enable_object (
    p_enabled      => TRUE, 
    p_schema       => 'RESTSCOTT',
    p_object       => 'CLIENT',
    p_object_type  => 'TABLE', 
    p_object_alias => 'client'
  );
    
  COMMIT;
END;
/
----------------------table commande----------------------
 BEGIN
  ORDS.enable_object (
    p_enabled      => TRUE, 
    p_schema       => 'RESTSCOTT',
    p_object       => 'COMMANDE',
    p_object_type  => 'TABLE', 
    p_object_alias => 'commande'
  );
    
  COMMIT;
END;
/

----------------------table ordinateur----------------------
 BEGIN
  ORDS.enable_object (
    p_enabled      => TRUE, 
    p_schema       => 'RESTSCOTT',
    p_object       => 'ORDINATEURS',
    p_object_type  => 'TABLE', 
    p_object_alias => 'ordinateurs'
  );
    
  COMMIT;
END;
/

----------------------table tablette----------------------
 BEGIN
  ORDS.enable_object (
    p_enabled      => TRUE, 
    p_schema       => 'RESTSCOTT',
    p_object       => 'TABLETTE',
    p_object_type  => 'TABLE', 
    p_object_alias => 'tablette'
  );
    
  COMMIT;
END;
/


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             4
-- CREATE INDEX                             0
-- ALTER TABLE                              7
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
